server:
  port: 8082
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/fooddelivery
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
